# Default values for rio-talks-mongodb-spring-data-mongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: localhost:5000/rio-talks-mongodb-spring-data-mongo
  tag: latest
  pullPolicy: Always
  imagePullSecrets: "docker"

nameOverride: ""
fullnameOverride: "rio-talks-mongodb-spring-data-mongo"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - "dev.local"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.class: "nginx"
  path: /rio-talks-mongodb-spring-data-mongo/?(.*)
  tls: [ ]

profile:
  active: "staging"

resources: { }
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
#  memory: 128Mi
# requests:
#  cpu: 100m
#  memory: 128Mi

nodeSelector: { }

tolerations: [ ]

affinity: { }
