apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "rio-talks-mongodb-spring-data-mongo.fullname" . } }
  labels:
    app.kubernetes.io/name: { { include "rio-talks-mongodb-spring-data-mongo.name" . } }
    helm.sh/chart: { { include "rio-talks-mongodb-spring-data-mongo.chart" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
    app.kubernetes.io/managed-by: { { .Release.Service } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app.kubernetes.io/name: { { include "rio-talks-mongodb-spring-data-mongo.name" . } }
      app.kubernetes.io/instance: { { .Release.Name } }
  template:
    metadata:
      labels:
        app.kubernetes.io/name: { { include "rio-talks-mongodb-spring-data-mongo.name" . } }
        app.kubernetes.io/instance: { { .Release.Name } }
    spec:
      imagePullSecrets:
        - name: { { .Values.image.imagePullSecrets } }
      containers:
        - name: { { .Chart.Name } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: { { .Values.service.port } }
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 150
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 150
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: { { .Values.profile.active } }
          resources:
  { { toYaml .Values.resources | indent 12 } }
  { { - with .Values.nodeSelector } }
nodeSelector:
  { { toYaml . | indent 8 } }
    { { - end } }
    { { - with .Values.affinity } }
affinity:
  { { toYaml . | indent 8 } }
    { { - end } }
    { { - with .Values.tolerations } }
tolerations:
  { { toYaml . | indent 8 } }
    { { - end } }
